add wave -noupdate -divider ESTADOS
add wave -noupdate /tb/dut/EA_R
add wave -noupdate /tb/dut/EA_C
add wave -noupdate /tb/dut/EA_W
add wave -noupdate -divider SINCRONISMO
add wave -noupdate -color black /tb/dut/rst
add wave -noupdate -color black /tb/dut/clk
add wave -noupdate -color black /tb/dut/start
add wave -noupdate -divider LEITURA
add wave -noupdate /tb/dut/EA_R
add wave -noupdate /tb/dut/PE_R
add wave -noupdate /tb/dut/Din
add wave -noupdate /tb/dut/base_VRd
add wave -noupdate -color purple -radix unsigned /tb/dut/cnt_col
add wave -noupdate -color purple -radix unsigned /tb/dut/current_IFchannel
add wave -noupdate -color purple -radix unsigned /tb/dut/current_OFchannel
add wave -noupdate -color purple -radix unsigned /tb/dut/cnt_convolutions
add wave -noupdate -color purple -radix unsigned /tb/dut/cnt_horiz_convs
add wave -noupdate -color purple -radix decimal /tb/dut/cnt_weight
add wave -noupdate -color purple -radix decimal /tb/dut/end_write_results
add wave -noupdate -color blue /tb/dut/horizontal_step
add wave -noupdate -divider {New Divider}
add wave -noupdate -color Red -radix unsigned /tb/dut/address
add wave -noupdate -color Red -radix unsigned /tb/dut/internal_address
add wave -noupdate -divider {New Divider}
add wave -noupdate -color purple -radix decimal -childformat {{{/tb/dut/Vrd[0]} -radix decimal} {{/tb/dut/Vrd[1]} -radix decimal} {{/tb/dut/Vrd[2]} -radix decimal} {{/tb/dut/Vrd[3]} -radix decimal} {{/tb/dut/Vrd[4]} -radix decimal} {{/tb/dut/Vrd[5]} -radix decimal} {{/tb/dut/Vrd[6]} -radix decimal} {{/tb/dut/Vrd[7]} -radix decimal} {{/tb/dut/Vrd[8]} -radix decimal} {{/tb/dut/Vrd[9]} -radix decimal} {{/tb/dut/Vrd[10]} -radix decimal} {{/tb/dut/Vrd[11]} -radix decimal} {{/tb/dut/Vrd[12]} -radix decimal} {{/tb/dut/Vrd[13]} -radix decimal} {{/tb/dut/Vrd[14]} -radix decimal} {{/tb/dut/Vrd[15]} -radix decimal} {{/tb/dut/Vrd[16]} -radix decimal} {{/tb/dut/Vrd[17]} -radix decimal} {{/tb/dut/Vrd[18]} -radix decimal} {{/tb/dut/Vrd[19]} -radix decimal} {{/tb/dut/Vrd[20]} -radix decimal} {{/tb/dut/Vrd[21]} -radix decimal} {{/tb/dut/Vrd[22]} -radix decimal} {{/tb/dut/Vrd[23]} -radix decimal} {{/tb/dut/Vrd[24]} -radix decimal}} -subitemconfig {{/tb/dut/Vrd[0]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[1]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[2]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[3]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[4]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[5]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[6]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[7]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[8]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[9]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[10]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[11]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[12]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[13]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[14]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[15]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[16]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[17]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[18]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[19]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[20]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[21]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[22]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[23]} {-color purple -height 21 -radix decimal} {/tb/dut/Vrd[24]} {-color purple -height 21 -radix decimal}} /tb/dut/Vrd
add wave -noupdate -color black /tb/dut/ce
add wave -noupdate -color red /tb/dut/last_line
add wave -noupdate -color red /tb/dut/lastIFMAP
add wave -noupdate -color red /tb/dut/lastOFMAP
add wave -noupdate -color purple -radix decimal /tb/dut/end_all_convolutions
add wave -noupdate -color purple -radix decimal -childformat {{{/tb/dut/convReg[0]} -radix decimal} {{/tb/dut/convReg[1]} -radix decimal} {{/tb/dut/convReg[2]} -radix decimal} {{/tb/dut/convReg[3]} -radix decimal} {{/tb/dut/convReg[4]} -radix decimal} {{/tb/dut/convReg[5]} -radix decimal} {{/tb/dut/convReg[6]} -radix decimal} {{/tb/dut/convReg[7]} -radix decimal} {{/tb/dut/convReg[8]} -radix decimal} {{/tb/dut/convReg[9]} -radix decimal} {{/tb/dut/convReg[10]} -radix decimal} {{/tb/dut/convReg[11]} -radix decimal} {{/tb/dut/convReg[12]} -radix decimal} {{/tb/dut/convReg[13]} -radix decimal} {{/tb/dut/convReg[14]} -radix decimal} {{/tb/dut/convReg[15]} -radix decimal} {{/tb/dut/convReg[16]} -radix decimal} {{/tb/dut/convReg[17]} -radix decimal} {{/tb/dut/convReg[18]} -radix decimal} {{/tb/dut/convReg[19]} -radix decimal} {{/tb/dut/convReg[20]} -radix decimal} {{/tb/dut/convReg[21]} -radix decimal} {{/tb/dut/convReg[22]} -radix decimal} {{/tb/dut/convReg[23]} -radix decimal} {{/tb/dut/convReg[24]} -radix decimal}} -subitemconfig {{/tb/dut/convReg[0]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[1]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[2]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[3]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[4]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[5]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[6]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[7]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[8]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[9]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[10]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[11]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[12]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[13]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[14]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[15]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[16]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[17]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[18]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[19]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[20]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[21]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[22]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[23]} {-color purple -height 21 -radix decimal} {/tb/dut/convReg[24]} {-color purple -height 21 -radix decimal}} /tb/dut/convReg
add wave -noupdate -color purple -radix decimal -childformat {{{/tb/dut/weightReg[0]} -radix decimal} {{/tb/dut/weightReg[1]} -radix decimal} {{/tb/dut/weightReg[2]} -radix decimal} {{/tb/dut/weightReg[3]} -radix decimal} {{/tb/dut/weightReg[4]} -radix decimal} {{/tb/dut/weightReg[5]} -radix decimal} {{/tb/dut/weightReg[6]} -radix decimal} {{/tb/dut/weightReg[7]} -radix decimal} {{/tb/dut/weightReg[8]} -radix decimal} {{/tb/dut/weightReg[9]} -radix decimal} {{/tb/dut/weightReg[10]} -radix decimal} {{/tb/dut/weightReg[11]} -radix decimal} {{/tb/dut/weightReg[12]} -radix decimal} {{/tb/dut/weightReg[13]} -radix decimal} {{/tb/dut/weightReg[14]} -radix decimal} {{/tb/dut/weightReg[15]} -radix decimal} {{/tb/dut/weightReg[16]} -radix decimal} {{/tb/dut/weightReg[17]} -radix decimal} {{/tb/dut/weightReg[18]} -radix decimal} {{/tb/dut/weightReg[19]} -radix decimal} {{/tb/dut/weightReg[20]} -radix decimal} {{/tb/dut/weightReg[21]} -radix decimal} {{/tb/dut/weightReg[22]} -radix decimal} {{/tb/dut/weightReg[23]} -radix decimal} {{/tb/dut/weightReg[24]} -radix decimal}} -subitemconfig {{/tb/dut/weightReg[0]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[1]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[2]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[3]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[4]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[5]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[6]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[7]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[8]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[9]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[10]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[11]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[12]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[13]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[14]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[15]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[16]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[17]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[18]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[19]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[20]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[21]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[22]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[23]} {-color purple -height 21 -radix decimal} {/tb/dut/weightReg[24]} {-color purple -height 21 -radix decimal}} /tb/dut/weightReg
add wave -noupdate -divider CONVOLUTION
add wave -noupdate /tb/dut/EA_C
add wave -noupdate /tb/dut/PE_C
add wave -noupdate -color red /tb/dut/end_conv
add wave -noupdate -color black /tb/dut/cnt_multip
add wave -noupdate -divider {MEMORY WRITE}
add wave -noupdate /tb/dut/EA_W
add wave -noupdate /tb/dut/PE_W
add wave -noupdate /tb/dut/contRd
add wave -noupdate /tb/dut/contWr
