# Validate the post-route simulation artifacts generated by synth_impl.tcl.
# XSim is launched by run_post_impl_saif.sh; this Tcl helper keeps the check
# reproducible when invoked from Vivado. No VCD is produced by this flow.
set script_dir [file dirname [file normalize [info script]]]
set bench_dir [file normalize [file join $script_dir ..]]
if {$argc < 1} { puts stderr "usage: post_impl_saif.tcl <run>"; exit 2 }
set run_name [lindex $argv 0]
set run_dir [file join $bench_dir reports $run_name]
foreach artifact {design_routed.dcp design_routed_timesim.v design_routed.sdf} {
  set path [file join $run_dir $artifact]
  if {![file exists $path]} {
    error "missing post-route artifact: $path"
  }
}
puts "POST_IMPL_ARTIFACTS_OK run=$run_name dir=$run_dir"
