#!/usr/bin/env bash
set -euo pipefail

# Run the routed timing netlist with XSim and emit SAIF only. VCD generation is
# deliberately opt-in through the separate POWER_DUMP macro and is not used by
# this campaign.
if [[ $# -ne 1 ]]; then
  printf 'usage: %s <run-name>\n' "$0" >&2
  exit 2
fi

script_dir=$(cd -- "$(dirname -- "$0")" && pwd)
bench_dir=$(cd -- "$script_dir/.." && pwd)
run_name=$1
run_dir="$bench_dir/reports/$run_name"
repo_root=$(cd -- "$bench_dir/../../../.." && pwd)

for tool in xvlog xelab xsim; do
  command -v "$tool" >/dev/null || {
    printf 'required tool not found: %s\n' "$tool" >&2
    exit 127
  }
done

for artifact in design_routed_timesim.v design_routed.sdf; do
  [[ -f "$run_dir/$artifact" ]] || {
    printf 'missing post-route artifact: %s\n' "$run_dir/$artifact" >&2
    exit 1
  }
done

pack_data="$bench_dir/data/pack_data.sv"
pack_param="$repo_root/rtl/conv2x2/pack-param/tcn4/pack_param.sv"
memory="$repo_root/rtl/mem/mem.sv"
tb="$bench_dir/tb/tb_power.sv"
[[ -f "$pack_data" ]] || {
  printf 'missing generated workload package: %s\n' "$pack_data" >&2
  exit 1
}
cd "$run_dir"

# These directories are generated by XSim and are scoped to this run.
rm -rf xsim.dir .Xil
xvlog -d GATE_LEVEL -sv "$pack_data" "$pack_param" "$memory" "$tb" \
  design_routed_timesim.v > xsim_compile.log 2>&1
xelab tb_power glbl -s tb_power_gate -debug typical \
  -L unisims_ver -L unimacro_ver -L secureip \
  -timescale 1ns/1ps \
  -sdfmax /tb_power/dut=design_routed.sdf > xsim_elab.log 2>&1
xsim tb_power_gate -tclbatch "$script_dir/xsim_saif.tcl" \
  > xsim_run.log 2>&1

[[ -s activity.saif ]] || {
  printf 'XSim completed without a non-empty activity.saif\n' >&2
  exit 1
}
printf 'SAIF_COMPLETE run=%s file=%s\n' "$run_name" "$run_dir/activity.saif"
