flowchart TB
    W(["WAIT"]) -->|"p_start"| AP(["AP"]) --> RW(["READ_WEIGHTS"])
    RW -->|"w_weight_done"| R10A(["R10A"])
    RW -->|"lastOFMAP"| W
    R10A -->|"r_addr_count_input==4"| R10B(["R10B"])
    R10B -->|"r_addr_count_input==4"| R15A(["R15A"])
    R15A -->|"r_addr_count_input==4"| R15B(["R15B"])
    R15B -->|"r_addr_count_input==4"| R15C(["R15C"])
    R15C -->|"r_addr_count_input==4"| X(["XFER"])
    X --> HW(["HOLD_WRITE"])
    HW -->|"w_write_done && !last_line"| R15A
    HW -->|"w_write_done && last_line"| NR(["NEXT_ROW"])
    NR -->|"lastIFMAP"| AP
    NR -->|"!lastIFMAP"| R10A
